- hosts: raspberrypi*
  remote_user: pi
  become: true
  roles:
    - role: mikolak.raspi-config
      raspi_config_update_packages: yes
      raspi_config_expanded_filesystem: yes
      raspi_config_locale: de_DE.UTF8
      raspi_config_timezone: Europe/Berlin
      raspi_config_replace_user:
        name: thomas
        path_to_ssh_key: "~/.ssh/id_rsa.pub"